# Only test one combination: "Visual Studio 12 + Win64 + Debug + DLL". We can
# test more combinations but AppVeyor just takes too long to finish (each
# combination takes ~15mins).
platform:
  - Win64

configuration:
  - Debug

environment:
  matrix:
    - language: php
      image: Visual Studio 2015
      BUILD_DLL: ON
      UNICODE: ON

# Our build scripts run tests automatically; we don't want AppVeyor
# to try to detect them itself.
test: off

before_build:
  - if %platform%==Win32 set generator=Visual Studio 12
  - if %platform%==Win64 set generator=Visual Studio 12 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - CALL ci\appveyor.bat

skip_commits:
  message: /.*\[skip appveyor\].*/
